std_msgs/Header header
bool clear
bool enable_pedals
bool enable_steering
bool enable_shifting
bool shift_from_park
bool coast_decel
float64 linear_velocity
float64 accel_cmd
float64 linear_accel
float64 linear_decel
float64 jerk_limit_throttle
float64 jerk_limit_brake
float64 yaw_command
float64 angular_accel
float64 lateral_accel

uint8 YAW_RATE_MODE=0
uint8 CURVATURE_MODE=1
uint8 steering_mode

uint8 SPEED_MODE=0
uint8 ACCEL_MODE=1
uint8 pedals_mode