#this message contains a fixed array of every built in type and a Message type

float32[8] t_float
float64[8] t_double
char[8] t_char
bool[8] t_bool
byte[8] t_octet
uint8[8] t_u8
int8[8] t_i8
uint16[8] t_u16
int16[8] t_i16
uint32[8] t_u32
int32[8] t_i32
uint64[8] t_u64
int64[8] t_i64
string[8] t_string
wstring[8] t_wstring
string<=8[8] t_bounded_string
wstring<=8[8] t_bounded_wstring
ExampleMessage[8] t_message